### ISSUE TITLE
Use select_for_update for updating task and worker states

### ISSUE THREAD

**Issue by jezdez** [jezdez/django-celery-monitor#14]
Currently we're using Django's automatic transaction management when we call `get_or_create` or `update_or_create`. We should in addition use [`select_for_update`](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#select-for-update) to make sure that the data we're writing to the TaskState and WorkerState models work as intended.

This is especially true if the Camera is deployed in a way that would have multiple instances run side by side for scalability reasons.

**Comment by MarkusH** [comment]
For `get_or_create()` Django does indeed not use `select_for_update()` which is fair as there's nothing to be altered in the returned record.

For `update_or_create()` Django did _not_ use `select_for_update()` [before Django 1.11](https://github.com/django/django/commit/d44afd889275473c97474cca19467d1509e0fcc1) ([Django issue #26804](https://code.djangoproject.com/ticket/26804)).

**Comment by jezdez** [comment]
@MarkusH Time to review #16?

**Comment by jezdez** [comment]
The main change is 46ccd452677ac50391f765c60ed421ffdad0c8dd.

**Comment by jezdez** [comment]
This was fixed in #16.
