### ISSUE TITLE
Monitor celery beat and store results

### ISSUE THREAD

**Issue by psychok7** [jezdez/django-celery-monitor#18]
hi @jezdez i just realized that you are not "storing" the celery beat scheduled tasks. The old django-celery integration allowed this so we could keep track if the beat was running properly. so i was wondering if that was intentional or not.

I remember a while ago i asked for something similar here https://github.com/celery/django-celery-results/issues/16 but maybe this might make sense in this project.

My recommendation was to save it to cache memory first and eventually dumping it in the database (could be the same table or a different table).

What do you think?

**Comment by jezdez** [comment]
@psychok7 I'm not sure I follow, django-celery-monitor monitors what's going on in the Celery cluster, which tasks run, what the workers do etc. To do that it stores the current tasks in the `TaskState` and `WorkerState` data models and shows the processed tasks and current workers in the Django admin under the "Celery Monitor" section. In case that section remains empty for you, you may not be running the `celery events` command as indicated in the documentation.

But if you'd like to save the Celery beat schedule via the Django admin you can use the [django-celery-beat](https://github.com/celery/django-celery-beat) app in addition to django-celery-monitor.

**Comment by psychok7** [comment]
@jezdez i am using `django-celery-beat` (and it works) it's just not storing.

i am running celery monitor with `celery -A proj events -l info --camera django_celery_monitor.camera.Camera --frequency=2.0` and beat with `celery -A proj beat -l info -S django`

**Comment by jezdez** [comment]
> On 10. May 2017, at 19:55, Nuno Khan <notifications@github.com> wrote:
> 
> @jezdez i am using django-celery-beat (and it works) it's just not storing.
> 

Hm, what is not being stored?

**Comment by psychok7** [comment]
@jezdez its's easier to show you. i have a celerybeat schedule for sending emails every 30 sec. when using `djcelery` and when i go to `admin/djcelery/taskstate/` with celerycam enabled, i get the following:

![screen](https://cloud.githubusercontent.com/assets/282284/25925077/2a154718-35de-11e7-8970-f51db6a77e12.png)

if celerycam is turned off, the tasks stop updating. Note this is the OLD behavior that i am used to previous to celery 4.

Now using celery-results, celery-beat and monitor i don't have the same behavior (which i find important for me to understand whats happening with my beat schedules and tasks).

I hope i have now explained myself correctly.

cheers

**Comment by jezdez** [comment]
@psychok7 That  behavior you saw in Celery 3 with djcelery is the same that happens with Celery 4, the behavior effectively hasn't changed. I'm not sure where this is failing to be honest, as it works for me.

Can you check if the email sending tasks are actually executed by `celery worker` and the django-celery-monitor camera isn't populating the TaskState model?

In the above example for how you call the celery commands, you're using `-A proj`, while the general gist is that you need to pass in the path to the celery object you've defined in the `celery.py` file of your project IIRC. E.g. I use these and they successfully populate the django-celery-monitor Task and Worker admin section:

- `celery -A myproject.celery:celery beat -l info -S django`
- `celery -A myproject.celery:celery events -l info -c django_celery_monitor.camera.Camera --frequency=2.0`
- `celery -A myproject.celery:celery worker -l info --events`

**Comment by jezdez** [comment]
To clarify, `myproject.celery:celery` consists of:

- `myproject` - name of the the Python package in which the `settings.py` and `celery.py` files live
- `celery` - name of the Python module in the `myproject` packages - `celery.py`
- `:celery` - name of the [Celery application](http://docs.celeryproject.org/en/latest/userguide/application.html) instance (e.g. `celery = Celery()` in `celery.py`). In the Celery docs that's sometimes referred to as just `app`.

**Comment by psychok7** [comment]
@jezdez i was able to solve my issue. it turns out i first had to upgrade celery 4.0.2 to https://github.com/celery/celery/commit/e812c5780b4006516116f059ab498e1f043bdd50 because of https://github.com/celery/celery/issues/3620

Since i am using queues i had to specify them in my settings file for celerybeat (the problem was that celerybeat was not picking up from the right queue it seems).

so i apart from upgrading celery i only had to:

# settings.py
```python
CELERYBEAT_SCHEDULE = {
    # Executes every day at 13:51 P.M
    'send-queued-emails-every-30-seconds': {
        'task': 'core.tasks.send_queued_emails',
        'schedule': timedelta(seconds=30),
        'options': {'queue': 'email_queue'}
    },
}
```
On my `core.tasks.py` i also had to change `@app.task(queue='email_queue')` to `@app.task()` 

Thanks for your help, it made me look into the right places.
