### ISSUE TITLE
TasksStates frozen on STARTED/RETRY

### ISSUE THREAD

**Issue by mdogo** [jezdez/django-celery-monitor#20]
Hi!

I am having an issue with some tasks that once they have successfuly finished do not update on admin panel, so they freeze with started or retry status.

I run celery monitor with:

```
celery -A proj events -l info --camera django_celery_monitor.camera.Camera
```

I didn't find anything in the logs for now.

**Comment by arnemorten** [comment]
How do you run your worker? Try adding an -E to force events. 

celery -A proj worker -l info -E

What does your task look like?

**Comment by jezdez** [comment]
Closing as @mdogo hasn't provided details. Feel free to reopen if needed.

**Comment by mdogo** [comment]
It seems that I have less frozen tasks, I don't know if there is a problem with some of my components. I will write again if I find the problem.

Thank you!
